const BancoPerguntas = [
  "Tive dificuldade em acalmar-me",
  "Estava consciente que minha boca estava seca",
  "Parecia não conseguir ter nenhum sentimento positivo",
  "Senti dificuldade em respirar (ex. respiração excessivamente rápida, falta de ar, na ausência de esforço físico)",
  "Tive dificuldade em tomar iniciativa para fazer as coisas",
  "Tive a tendência de reagir de forma exagerada a situações",
  "Senti tremores (ex. nas mãos)",
  "Senti que estava geralmente muito nervoso",
  "Preocupei-me com situações em que eu pudesse entrar em pânico e parecesse ridículo (a)",
  "Senti que não tinha nada a esperar do futuro",
  "Senti que estava agitado",
  "Tive dificuldade em relaxar",
  "Senti-me desanimado e deprimido",
  "Fui intolerante com as coisas que impediam-me de continuar o que eu estava fazendo",
  "Senti que ia entrar em pânico",
  "Não consegui me entusiasmar com nada",
  "Senti que não tinha muito valor como pessoa",
  "Senti que estava sensível",
  "Eu estava consciente do funcionamento/batimento do meu coração na ausência de esforço físico (ex. sensação de aumento da frequência cardíaca, disritmia cardíaca)",
  "Senti-me assustado sem ter uma boa razão",
  "Senti que a vida estava sem sentido",
];

export default BancoPerguntas;
